# --- TEST PING SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-test
  namespace: test
  labels:
    app: ping
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
      env: test
  template:
    metadata:
      labels:
        app: ping
        env: test
    spec:
      containers:
        - name: ping
          image: eyupcanbay/ping-service:38b636b10edf7ed11d1d0059a9abfb39cb1b405a
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ping-port
            - name: PONG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: pong-url
---
apiVersion: v1
kind: Service
metadata:
  name: ping-test
  namespace: test
  labels:
    app: ping
spec:
  selector:
    app: ping
    env: test
  type: NodePort
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080

---
# --- TEST PONG SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-test
  namespace: test
  labels:
    app: pong
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
      env: test
  template:
    metadata:
      labels:
        app: pong
        env: test
    spec:
      containers:
        - name: pong
          image: eyupcanbay/pong-service:38b636b10edf7ed11d1d0059a9abfb39cb1b405a
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: pong-port
            - name: PING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ping-url
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pong-test
  namespace: test
  labels:
    app: pong
spec:
  selector:
    app: pong
    env: test
  type: ClusterIP
  ports:
    - name: http-port
      port: 8081
      targetPort: 8081