name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: eyupcanbay
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Ping Service
        uses: docker/build-push-action@v5
        with:
          context: ./ping-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ping-service:latest

      - name: Build and Push Pong Service
        uses: docker/build-push-action@v5
        with:
          context: ./pong-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pong-service:latest